import { useState, type FormEvent } from 'react'
import type { OperationOffer } from '../../lib/api'
import type { MarketWriter, SubmittedTransaction } from '../../lib/marketContract'

export function Offers({ offers, writer, submit }: { offers: OperationOffer[]; writer: MarketWriter; submit: (action:()=>Promise<SubmittedTransaction>)=>Promise<void> }) {
  const [id,setID]=useState(''); const [model,setModel]=useState(''); const [input,setInput]=useState(''); const [output,setOutput]=useState(''); const [compute,setCompute]=useState(''); const [workspace,setWorkspace]=useState(false)
  const publish=async(event:FormEvent)=>{event.preventDefault();for(const value of [input,output,compute]) if(!/^\d+$/.test(value)) throw new Error('Prices must be integer wei.');await submit(()=>writer.publishOffer({offerID:id,model,capabilities:workspace?['text','stream','workspace']:['text','stream'],inputPerMillion:BigInt(input),outputPerMillion:BigInt(output),computePerSecond:BigInt(compute)}))}
  return <div className="offer-operations"><h3>Immutable offer versions</h3><ul>{offers.map((offer)=><li key={`${offer.offer_id}:${offer.version}`}><code>{offer.offer_id}</code><strong>Version {offer.version}</strong><span>{offer.input_per_million_wei} / {offer.output_per_million_wei} / {offer.compute_per_second_wei} wei</span></li>)}</ul><form onSubmit={(event)=>void publish(event)}><label htmlFor="offer-id">Offer name</label><input id="offer-id" value={id} onChange={(event)=>setID(event.target.value)} required /><label htmlFor="offer-model">Model</label><input id="offer-model" value={model} onChange={(event)=>setModel(event.target.value)} required /><label htmlFor="offer-workspace"><input id="offer-workspace" type="checkbox" checked={workspace} onChange={(event)=>setWorkspace(event.target.checked)} /> Temporary workspace (CLI agents only)</label><label htmlFor="offer-input">Input / 1M (wei)</label><input id="offer-input" value={input} onChange={(event)=>setInput(event.target.value)} required /><label htmlFor="offer-output">Output / 1M (wei)</label><input id="offer-output" value={output} onChange={(event)=>setOutput(event.target.value)} required /><label htmlFor="offer-compute">Compute / second (wei)</label><input id="offer-compute" value={compute} onChange={(event)=>setCompute(event.target.value)} required /><button type="submit">Publish next offer version</button></form></div>
}
