import { useQuery } from '@tanstack/react-query'
import { Activity, Banknote, Clock3, ShieldAlert } from 'lucide-react'
import { AnalyticsAPI } from '../../lib/api'
import { DailyChart } from './UsageAnalytics'
import { Money } from '../../components/Money'

export function ProviderAnalytics({ api = new AnalyticsAPI() }: { api?: AnalyticsAPI }) {
  const analytics = useQuery({ queryKey: ['account-analytics'], queryFn: () => api.analytics(), retry: false, refetchInterval: 15_000 })
  if (analytics.isPending) return <div className="dashboard-empty" role="status"><strong>Loading confirmed provider analytics…</strong></div>
  if (analytics.isError) return <div className="dashboard-empty" role="alert"><strong>Provider analytics are unavailable</strong><p>Reconnect the wallet or wait for the indexer to catch up.</p></div>
  const { provider, daily, settlements, slashes } = analytics.data
  const metrics = [{ label: 'Settled requests', value: provider.settled_requests, icon: Activity }, { label: 'Tokens served', value: provider.input_tokens + provider.output_tokens, icon: Activity }, { label: 'Compute served', value: `${provider.compute_milliseconds} ms`, icon: Clock3 }, { label: 'Gross revenue', wei: provider.gross_revenue_wei, icon: Banknote }, { label: 'Total slashed', wei: provider.total_slashed_wei, icon: ShieldAlert }]
  return <div className="analytics-panel"><div className="analytics-metrics">{metrics.map(({ label, value, wei, icon: Icon }) => <article key={label}><Icon size={18} aria-hidden="true" /><span>{label}</span><strong>{wei === undefined ? value : <Money wei={wei}/>}</strong></article>)}</div><section className="analytics-section"><p className="eyebrow">Last 30 days</p><h2>Settled provider requests</h2><DailyChart days={daily} field="provider_requests" /></section><section className="analytics-section"><p className="eyebrow">Revenue ledger</p><h2>Recent settlements</h2>{settlements.length === 0 ? <p className="activity-empty">No provider settlements confirmed yet.</p> : <div className="analytics-table">{settlements.map((item) => <div className="analytics-row provider" key={item.request_id}><div><code>{item.request_id}</code><small>{item.model}</small></div><span>{item.input_tokens + item.output_tokens} tokens</span><span>{item.compute_milliseconds} ms</span><strong><Money wei={item.revenue_wei}/></strong><code>{item.transaction_hash}</code></div>)}</div>}</section><section className="analytics-section"><p className="eyebrow">Collateral enforcement</p><h2>Slashing history</h2>{slashes.length === 0 ? <p className="activity-empty">No confirmed slashing events for this provider.</p> : <div className="analytics-table">{slashes.map((item) => <div className="analytics-row slash" key={`${item.request_id}:${item.transaction_hash}`}><code>{item.request_id}</code><strong><Money wei={item.amount_wei}/></strong><span>Block {item.block_number}</span><code>{item.transaction_hash}</code><time dateTime={item.indexed_at}>{new Date(item.indexed_at).toLocaleString()}</time></div>)}</div>}</section></div>
}
